"""Synchronize only manuscript assets that are still used by the current paper.

This helper deliberately does not rewrite references, Elsevier template files,
or manuscript text. Comparator- and extension-specific tables are generated by
their own analysis modules.
"""
import csv
import gzip
import json
import hashlib
import shutil
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]


def main():
    paper = ROOT / "paper"

    # Supplementary informed-attacker table from the frozen stress evidence.
    summary = list(csv.DictReader((ROOT / "results/informed/analysis/summary.csv").open()))
    lines = [
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r"Client mismatch & Retention & MAP hit & Above cap & Largest peak \\",
        r"\midrule",
    ]
    detail = []
    for cid, label in [
        ("alpha_model_0.3", r"$\widehat\alpha=0.3$"),
        ("alpha_model_0.9", r"$\widehat\alpha=0.9$"),
        ("move_model_0.05", r"$\widehat v=0.05$"),
        ("move_model_0.8", r"$\widehat v=0.8$"),
    ]:
        path = ROOT / f"results/informed/informed_{cid}_bsp.jsonl.gz"
        events = [e for line in gzip.open(path, "rt") for e in json.loads(line)["events"]]
        peaks = np.array([max(e["belief"]) for e in events])
        row = next(r for r in summary if r["condition"] == "informed_" + cid + "_bsp")
        frac = float(np.mean(peaks > .1 + 1e-9))
        maximum = float(peaks.max())
        lines.append(
            label
            + f" & {float(row['utility']):.3f} & {float(row['hit']):.3f} & "
            + f"{100*frac:.1f}\\% & {maximum:.3f} "
            + r"\\"
        )
        detail.append(
            dict(
                condition=row["condition"],
                fraction_above_cap=frac,
                maximum_peak=maximum,
                events=len(events),
                source=str(path.relative_to(ROOT)),
                sha256=hashlib.sha256(path.read_bytes()).hexdigest(),
            )
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    (paper / "informed_table.tex").write_text("\n".join(lines) + "\n")
    (ROOT / "results/informed/analysis/cap_audit.json").write_text(
        json.dumps(detail, indent=2) + "\n"
    )

    # Only PDFs referenced by the current supplement are copied to paper/.
    copies = {
        ROOT / "results/combined/analysis/tradeoff.pdf": paper / "tradeoff.pdf",
        ROOT / "results/combined/analysis/calibration.pdf": paper / "calibration.pdf",
        ROOT / "results/sensitivity/analysis/sensitivity.pdf": paper / "sensitivity.pdf",
        ROOT / "results/recent_comparison/recent_tradeoff.pdf": paper / "recent_tradeoff.pdf",
        ROOT / "results/review1_diagnostics/recent_commute_zoom.pdf": paper / "recent_commute_zoom.pdf",
    }
    for src, dst in copies.items():
        shutil.copyfile(src, dst)

    print("Synchronized", len(copies), "current manuscript figures and informed_table.tex")


if __name__ == "__main__":
    main()
